"""Initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-01 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_requests',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('requester_did', sa.String(), nullable=False),
        sa.Column('asset_serial', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('signature', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_requests_asset_serial'), 'access_requests', ['asset_serial'], unique=False)
    op.create_index(op.f('ix_access_requests_requester_did'), 'access_requests', ['requester_did'], unique=False)

    op.create_table('audit_events',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('event_type', sa.String(), nullable=False),
        sa.Column('tx_hash', sa.String(), nullable=False),
        sa.Column('block_number', sa.Integer(), nullable=False),
        sa.Column('actor_did', sa.String(), nullable=True),
        sa.Column('target_did', sa.String(), nullable=True),
        sa.Column('asset_serial', sa.String(), nullable=True),
        sa.Column('risk_score', sa.Float(), nullable=True),
        sa.Column('risk_label', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_block_number'), 'audit_events', ['block_number'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_tx_hash'), 'audit_events', ['tx_hash'], unique=True)

    op.create_table('users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('wallet_address', sa.String(length=42), nullable=False),
        sa.Column('did', sa.String(), nullable=True),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_did'), 'users', ['did'], unique=True)
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)

    op.create_table('assets',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('token_id', sa.Integer(), nullable=False),
        sa.Column('serial_number', sa.String(), nullable=False),
        sa.Column('metadata_cid', sa.String(), nullable=True),
        sa.Column('owner_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_serial_number'), 'assets', ['serial_number'], unique=True)
    op.create_index(op.f('ix_assets_token_id'), 'assets', ['token_id'], unique=True)

    op.create_table('verifiable_credentials',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('vc_jwt', sa.Text(), nullable=False),
        sa.Column('issuer_did', sa.String(), nullable=False),
        sa.Column('subject_did', sa.String(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verifiable_credentials')
    op.drop_index(op.f('ix_assets_token_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_serial_number'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_index(op.f('ix_users_did'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_audit_events_tx_hash'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_block_number'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_access_requests_requester_did'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_asset_serial'), table_name='access_requests')
    op.drop_table('access_requests')
    # ### end Alembic commands ###
